version: "3.8"

services:
  musicbox:
    image: musicbox
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./:/app
    entrypoint: ["yarn", "run", "dev", "--host", "0.0.0.0"] # run ["yarn"] first time